language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to run tests
script:
  - ./109titration -h
  - ./109titration values.csv
  - ./109titration ; if [[ $(echo $?) == 84 ]]; then exit 0; else exit 84; fi
  - ./109titration unexistant_file ; if [[ $(echo $?) == 84 ]]; then exit 0; else exit 84; fi
  - ./109titration invalid.csv ; if [[ $(echo $?) == 84 ]]; then exit 0; else exit 84; fi
